using Org.BouncyCastle.Asn1;
using Org.BouncyCastle.Asn1.TeleTrust;
using Org.BouncyCastle.Math;
using Org.BouncyCastle.Math.EC;

namespace PolymorphicPseudonymisation.Crypto
{
    /// <summary>
    /// BrainpoolP320r1 conform RFC 5639
    /// </summary>
    public static class BrainpoolP320R1
    {
        public static readonly DerObjectIdentifier ObjectIdentifier = TeleTrusTObjectIdentifiers.BrainpoolP320R1;

        /// <summary>
        /// Elliptic curve
        /// </summary>
        public static readonly ECCurve Curve = TeleTrusTNamedCurves.GetByOid(ObjectIdentifier).Curve;

        /// <summary>
        /// Base point
        /// </summary>
        public static readonly ECPoint G = TeleTrusTNamedCurves.GetByOid(ObjectIdentifier).G;

        /// <summary>
        /// Prime order of the group generated by G
        /// </summary>
        public static readonly BigInteger Q = TeleTrusTNamedCurves.GetByOid(ObjectIdentifier).N;
    }
}
